import { DEFAULT_EVENT_BUFFER, DEFAULT_PI_COMMAND, abortError, createAsyncQueue, onceAbort, positiveInteger } from "./helpers";
import { type PiRequestId, type PiRpcCommand, type PiRpcEvent, encodePiCommand, parsePiFrame } from "./protocol";

export interface PiModelAttribution { readonly requestedProvider?: string; readonly requestedModel?: string; readonly resolvedProvider?: string; readonly resolvedModel?: string; readonly fallback: "yes" | "no" | "unknown" }
export interface PiUsage { readonly input?: number; readonly output?: number; readonly total?: number; readonly cost?: number }
export interface PiExecutionEvent { readonly sequence: number; readonly receivedAt: number; readonly event: PiRpcEvent; readonly model: PiModelAttribution; readonly usage?: PiUsage }
export interface PiTerminalResult { readonly ok: boolean; readonly sessionId: string; readonly stopReason?: string; readonly text: string; readonly usage?: PiUsage; readonly model: PiModelAttribution; readonly error?: string }
export interface PiExecutionSession { readonly sessionId: string; readonly sessionFile?: string; readonly events: AsyncIterable<PiExecutionEvent>; prompt(message: string, signal?: AbortSignal): Promise<PiTerminalResult>; steer(message: string): Promise<void>; followUp(message: string): Promise<void>; setModel(provider: string, modelId: string): Promise<void>; cancel(reason?: string): Promise<void>; resume(): Promise<PiExecutionSession>; dispose(): Promise<void> }
export interface PiBackendRequest { readonly prompt?: string; readonly sessionId?: string; readonly sessionFile?: string; readonly provider?: string; readonly model?: string; readonly cwd?: string; readonly signal?: AbortSignal }
export interface PiRpcProcess { readonly stdin: { write(data: string): unknown }; readonly stdout: ReadableStream<Uint8Array>; readonly exited: Promise<number>; kill(): void }
export interface PiBackendOptions { readonly command?: string; readonly args?: readonly string[]; readonly cwd?: string; readonly env?: Record<string, string | undefined>; readonly sessionDir?: string; readonly maxEventBuffer?: number; readonly cancelTimeoutMs?: number; readonly spawn?: (command: readonly string[], options: { cwd?: string; env?: Record<string, string | undefined> }) => PiRpcProcess }
interface PiResolvedBackendOptions { readonly command: string; readonly maxEventBuffer: number; readonly cancelTimeoutMs: number; readonly args?: readonly string[]; readonly cwd?: string; readonly env?: Record<string, string | undefined>; readonly sessionDir?: string; readonly spawn?: PiBackendOptions["spawn"] }
interface PendingResponse { readonly resolve: (response: ResponseFrame) => void; readonly reject: (error: Error) => void }
interface ResponseFrame { readonly success: boolean; readonly data?: unknown }

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) }
function record(value: unknown): Record<string, unknown> | undefined { return isRecord(value) ? value : undefined }
function stringValue(value: unknown, ...keys: string[]): string | undefined { const source = record(value); if (!source) return undefined; for (const key of keys) if (typeof source[key] === "string") return source[key]; return undefined }
function numberValue(value: unknown, ...keys: string[]): number | undefined { const source = record(value); if (!source) return undefined; for (const key of keys) if (typeof source[key] === "number" && Number.isFinite(source[key])) return source[key]; return undefined }
function nestedSources(event: PiRpcEvent): Record<string, unknown>[] { const source = record(event); if (!source) return []; const message = record(source.message); const assistantMessageEvent = record(source.assistantMessageEvent); return [source, ...(message ? [message] : []), ...(assistantMessageEvent ? [assistantMessageEvent] : [])] }
function firstString(sources: Record<string, unknown>[], ...keys: string[]): string | undefined { for (const source of sources) { const value = stringValue(source, ...keys); if (value !== undefined) return value } return undefined }
function modelFrom(event: PiRpcEvent, requestedProvider?: string, requestedModel?: string, previous?: PiModelAttribution): PiModelAttribution { const sources = nestedSources(event); const resolvedProvider = firstString(sources, "provider", "resolvedProvider") ?? previous?.resolvedProvider; const resolvedModel = firstString(sources, "model", "modelId", "resolvedModel") ?? previous?.resolvedModel; const fallback = resolvedProvider && resolvedModel ? resolvedProvider !== requestedProvider || resolvedModel !== requestedModel ? "yes" : "no" : "unknown"; return { requestedProvider, requestedModel, resolvedProvider, resolvedModel, fallback } }
function usageFrom(event: PiRpcEvent): PiUsage | undefined { const sources = nestedSources(event); const usage = record(record(event)?.usage); const usageSources = usage ? [usage, ...sources] : sources; const input = usageSources.map(source => numberValue(source, "input", "inputTokens", "input_tokens")).find(value => value !== undefined); const output = usageSources.map(source => numberValue(source, "output", "outputTokens", "output_tokens")).find(value => value !== undefined); const total = usageSources.map(source => numberValue(source, "total", "totalTokens", "total_tokens")).find(value => value !== undefined); const cost = usageSources.map(source => numberValue(source, "cost", "totalCost")).find(value => value !== undefined); return input === undefined && output === undefined && total === undefined && cost === undefined ? undefined : { input, output, total, cost } }
function textFrom(event: PiRpcEvent): string { const source = record(event); const assistantMessageEvent = record(source?.assistantMessageEvent); if (source?.type === "message_update") return stringValue(assistantMessageEvent, "delta") ?? stringValue(source, "delta") ?? ""; return firstString(nestedSources(event), "text", "content") ?? "" }

export class PiRpcBackend {
	readonly #options: PiResolvedBackendOptions;
	constructor(options: PiBackendOptions = {}) { this.#options = { ...options, command: options.command ?? DEFAULT_PI_COMMAND, maxEventBuffer: positiveInteger(options.maxEventBuffer, DEFAULT_EVENT_BUFFER), cancelTimeoutMs: positiveInteger(options.cancelTimeoutMs, 5000) }; }
	async start(request: PiBackendRequest = {}): Promise<PiExecutionSession> {
		const args = [this.#options.command, ...(this.#options.args ?? []), "--mode", "rpc"];
		if (this.#options.sessionDir) args.push("--session-dir", this.#options.sessionDir);
		if (request.sessionFile) args.push("--session", request.sessionFile);
		if (request.sessionId) args.push("--session-id", request.sessionId);
		if (request.provider) args.push("--provider", request.provider);
		if (request.model) args.push("--model", request.model);
		const spawn = this.#options.spawn ?? ((command, options) => Bun.spawn([...command], { cwd: options.cwd, env: options.env, stdin: "pipe", stdout: "pipe", stderr: "pipe" }));
		const process = spawn(args, { cwd: request.cwd ?? this.#options.cwd, env: this.#options.env });
		const session = new PiRpcExecutionSession(process, args, request, this.#options);
		if (request.prompt) void session.prompt(request.prompt, request.signal);
		return session;
	}
}

class PiRpcExecutionSession implements PiExecutionSession {
	readonly #process: PiRpcProcess; readonly #args: readonly string[]; readonly #request: PiBackendRequest; readonly #options: PiResolvedBackendOptions; readonly #queue: ReturnType<typeof createAsyncQueue<PiExecutionEvent>>; readonly #pending = new Map<PiRequestId, PendingResponse>(); readonly #terminal: Promise<PiTerminalResult>; readonly #resolveTerminal: (result: PiTerminalResult) => void; readonly #rejectTerminal: (error: Error) => void;
	#sequence = 0; #requestId = 0; #sessionId = ""; #sessionFile: string | undefined; #disposed = false; #settled = false; #text = ""; #model: PiModelAttribution; #usage: PiUsage | undefined;
    constructor(process: PiRpcProcess, args: readonly string[], request: PiBackendRequest, options: PiResolvedBackendOptions) { this.#process = process; this.#args = args; this.#request = request; this.#options = options; this.#queue = createAsyncQueue(options.maxEventBuffer); this.#model = { requestedProvider: request.provider, requestedModel: request.model, fallback: "unknown" }; let resolveTerminal!: (result: PiTerminalResult) => void; let rejectTerminal!: (error: Error) => void; this.#terminal = new Promise<PiTerminalResult>((resolve, reject) => { resolveTerminal = resolve; rejectTerminal = reject }); this.#resolveTerminal = resolveTerminal; this.#rejectTerminal = rejectTerminal; void this.#readOutput() }
	get events(): AsyncIterable<PiExecutionEvent> { return this.#queue.values }
	get sessionId(): string { return this.#sessionId || this.#request.sessionId || "unknown" }
	get sessionFile(): string | undefined { return this.#sessionFile }
	async prompt(message: string, signal?: AbortSignal): Promise<PiTerminalResult> { if (this.#disposed) throw new Error("Pi session is disposed"); const removeAbort = onceAbort(signal, () => { void this.cancel("aborted") }); try { await this.#send({ type: "prompt", message, id: this.#nextId() }); return await this.#terminal } finally { removeAbort() } }
	async steer(message: string): Promise<void> { await this.#send({ type: "steer", message, id: this.#nextId() }) }
	async followUp(message: string): Promise<void> { await this.#send({ type: "follow_up", message, id: this.#nextId() }) }
	async setModel(provider: string, modelId: string): Promise<void> { await this.#send({ type: "set_model", provider, modelId, id: this.#nextId() }) }
	async cancel(reason?: string): Promise<void> { if (this.#disposed) return; try { await this.#send({ type: "abort", id: this.#nextId() }) } catch {} await Promise.race([this.#terminal.catch(() => undefined), new Promise<void>(resolve => setTimeout(resolve, this.#options.cancelTimeoutMs))]); if (!this.#settled) this.#finish({ ok: false, sessionId: this.sessionId, text: this.#text, usage: this.#usage, model: this.#model, stopReason: "aborted", error: reason ?? "aborted" }) }
	async resume(): Promise<PiExecutionSession> { const sessionId = this.sessionId; const sessionFile = this.#sessionFile; await this.dispose(); const backend = new PiRpcBackend({ ...this.#options, args: this.#args.slice(1, this.#args.indexOf("--mode")) }); return backend.start({ ...this.#request, sessionId, sessionFile }) }
	async dispose(): Promise<void> { if (this.#disposed) return; this.#disposed = true; for (const pending of this.#pending.values()) pending.reject(new Error("Pi process disposed")); this.#pending.clear(); this.#queue.close(); this.#process.kill(); await this.#process.exited }
	async #send(command: PiRpcCommand): Promise<ResponseFrame> { if (this.#disposed) throw new Error("Pi session is disposed"); const id = command.id; if (id === undefined) throw new Error("Pi lifecycle commands require request ids"); const response = new Promise<ResponseFrame>((resolve, reject) => this.#pending.set(id, { resolve, reject })); try { this.#process.stdin.write(encodePiCommand(command)) } catch (error) { this.#pending.delete(id); throw abortError(error) } return response }
	#nextId(): number { this.#requestId += 1; return this.#requestId }
	#finish(result: PiTerminalResult): void { if (this.#settled) return; this.#settled = true; this.#resolveTerminal(result) }
	async #readOutput(): Promise<void> { try { const reader = this.#process.stdout.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!this.#disposed) { const next = await reader.read(); if (next.done) break; buffer += decoder.decode(next.value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; const event = parsePiFrame(line); if (event.type === "response" && event.id !== undefined) { const pending = this.#pending.get(event.id); if (pending) { this.#pending.delete(event.id); event.success ? pending.resolve({ success: true, data: event.data }) : pending.reject(new Error(event.error ?? `Pi ${event.command} failed`)) } continue } if (event.type === "session") { this.#sessionId = event.id; this.#sessionFile = event.sessionFile } this.#model = modelFrom(event, this.#request.provider, this.#request.model, this.#model); this.#usage = usageFrom(event) ?? this.#usage; if (event.type === "message_update") this.#text += textFrom(event); const normalized: PiExecutionEvent = { sequence: ++this.#sequence, receivedAt: Date.now(), event, model: this.#model, usage: this.#usage }; this.#queue.push(normalized); if (event.type === "agent_end") this.#finish({ ok: true, sessionId: this.sessionId, stopReason: stringValue(event, "stopReason", "stop_reason"), text: this.#text, usage: this.#usage, model: this.#model }) } } this.#queue.close(); if (!this.#settled && !this.#disposed) this.#rejectTerminal(new Error("Pi process ended before agent_end")) } catch (error) { this.#queue.close(abortError(error)); if (!this.#settled) this.#rejectTerminal(abortError(error)) } }
}

export function createPiBackend(options: PiBackendOptions = {}): PiRpcBackend { return new PiRpcBackend(options) }
